server:
  config:
    persistence:
      default:
        sql:
          pluginName: "postgres12"
          host: "vultr-prod-a83111d1-50b2-43e9-b1b6-853269bfdd16-vultr-prod-bf45.vultrdb.com"
          port: 16751
          user: "vultradmin"
          password: "AVNS_yjJMB7_CW7xDKKEQJ1R"
          database: "temporal"
      visibility:
        sql:
          pluginName: "postgres12"
          host: "vultr-prod-a83111d1-50b2-43e9-b1b6-853269bfdd16-vultr-prod-bf45.vultrdb.com"
          port: 16751
          user: "vultradmin"
          password: "AVNS_yjJMB7_CW7xDKKEQJ1R"
          database: "temporal_visibility"
elasticsearch:
  enabled: false
prometheus:
  enabled: false
grafana:
  enabled: false
